/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppResults {
    'searchResults': any[];
  }
  interface AppRoot {}
  interface AppSearch {}
  interface ResultFormGroup {
    'label': string;
    'value': string;
  }
}

declare global {


  interface HTMLAppResultsElement extends Components.AppResults, HTMLStencilElement {}
  var HTMLAppResultsElement: {
    prototype: HTMLAppResultsElement;
    new (): HTMLAppResultsElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSearchElement extends Components.AppSearch, HTMLStencilElement {}
  var HTMLAppSearchElement: {
    prototype: HTMLAppSearchElement;
    new (): HTMLAppSearchElement;
  };

  interface HTMLResultFormGroupElement extends Components.ResultFormGroup, HTMLStencilElement {}
  var HTMLResultFormGroupElement: {
    prototype: HTMLResultFormGroupElement;
    new (): HTMLResultFormGroupElement;
  };
  interface HTMLElementTagNameMap {
    'app-results': HTMLAppResultsElement;
    'app-root': HTMLAppRootElement;
    'app-search': HTMLAppSearchElement;
    'result-form-group': HTMLResultFormGroupElement;
  }
}

declare namespace LocalJSX {
  interface AppResults extends JSXBase.HTMLAttributes<HTMLAppResultsElement> {
    'searchResults'?: any[];
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface AppSearch extends JSXBase.HTMLAttributes<HTMLAppSearchElement> {
    'onSearchCompleted'?: (event: CustomEvent<any>) => void;
  }
  interface ResultFormGroup extends JSXBase.HTMLAttributes<HTMLResultFormGroupElement> {
    'label'?: string;
    'value'?: string;
  }

  interface IntrinsicElements {
    'app-results': AppResults;
    'app-root': AppRoot;
    'app-search': AppSearch;
    'result-form-group': ResultFormGroup;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


